---
name: Container Test

"on":
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-test:
    name: Container Test
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/container-test.yml@5d8d0f00346daa26a7dd1283ecd098bbcd2b5396 # v4.1.1
    with:
      containerfile-path: Dockerfile
