---
name: Container Release

"on":
  push:
    tags:
      - "*"

permissions: {}

jobs:
  container-release:
    name: Container Release
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/container-release.yml@49cbc73f4ba59d6c4a2458f0d7d56ae640943df5 # v4.0.11
    with:
      containerfile-path: Dockerfile
