---
name: Super Linter

"on":
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/super-linter.yml@82df95393d34df015c468f09e44890271448de16 # v4.0.12
    with:
      super-linter-variables: |
        {
          "LINTER_RULES_PATH": "."
        }
